# Generated by Django 3.2.3 on 2022-04-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='addr_pro',
            new_name='city',
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.TextField(default='lko'),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.TextField(default='lko'),
        ),
    ]
