# Generated by Django 3.2.3 on 2022-04-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220428_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.TextField(default='Lucknow'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.TextField(default='UttarPradesh'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.TextField(default='255/92 Rakabganj'),
        ),
    ]
