# Generated by Django 3.2.3 on 2022-04-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220428_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ph_pro',
            field=models.BigIntegerField(default='Not Available'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.TextField(default='Not Available'),
        ),
    ]
