# Generated by Django 3.2.3 on 2022-05-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220501_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ph_pro',
            field=models.BigIntegerField(default='123456789'),
        ),
    ]
