from django.urls import path
from.import views
urlpatterns=[
    path('',views.home,name='home'),
    path('aboutus/',views.aboutus,name='aboutus'),
    path('contactus/',views.Contact,name='contactus'),
    path('cart/',views.Cart,name='cart'),
    path("remove_ser",views.remove_ser,name="remove_ser"),
    path("get_cart_data",views.get_cart_data,name="get_cart_data"),
    path('repaircentre/',views.repaircentre,name='repaircentre'),
    path('rerv/<int:rid>',views.repaircentre1,name='repaircentre1'),
    path('services/',views.services,name='services'),
    path('rerv/serv/<int:sid>',views.services1,name='services1'),
    path('checkout/',views.checkout,name='checkout'),
    path("process_payment",views.process_payment,name="process_payment"),
    path("payment_done",views.payment_done,name="payment_done"),
    path("payment_cancelled",views.payment_cancelled,name="payment_cancelled"),
    path('addcatser/',views.add_ser,name='addser'),
    path('repairhome/',views.repairhome,name='repairhome'),
    path('repahm',views.repairaj,name="repaj"),
    path('bookingdetails/',views.bookingdet,name='bookingdetails'),
    path('billingdetails/',views.billingdet,name='billingdetails'),
    path('checkout/',views.billingdet,name='checkout'),
    path('shopdesc/',views.shopdesc,name='shopdesc'),
    path("postreview/<int:rid>", views.postreview, name="PostReview"),
    path("feedback",views.feed,name="feedback"),
    path("cash_on_delivery",views.cash_on_delivery,name="cash_on_delivery"),
    path("viewbookings",views.viewbook,name="viewbookings"),
    path("track/",views.tracking,name="track"),
    path("cancelproduct/", views.cancelProduct, name="CancelProduct"),
    #path('rerv/serv/adse/<int:adid>',views.catalogue1,name='catalogue1'),
]
