# Generated by Django 3.2.3 on 2022-04-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(max_length=25)),
                ('img_cat', models.ImageField(upload_to='media')),
                ('desc_cat', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ser', models.CharField(max_length=25)),
                ('desc_ser', models.TextField()),
                ('img_ser', models.ImageField(upload_to='media')),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
