# Generated by Django 3.2.3 on 2022-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service_cate'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_ser',
            field=models.IntegerField(default='1000'),
        ),
    ]
