# Generated by Django 3.2.3 on 2022-05-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_service_price_ser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price_ser',
        ),
    ]
