# Generated by Django 3.2.3 on 2022-05-03 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220503_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.repair_centre'),
        ),
    ]
