# Generated by Django 3.2.3 on 2022-05-03 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_service_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='addservices',
            name='shpp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.service'),
        ),
    ]
