# Generated by Django 3.2.3 on 2022-05-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_shpp_addservices_adserv'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_ser',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='addservices',
        ),
    ]
