# Generated by Django 3.2.3 on 2022-05-12 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=40)),
                ('modelname', models.CharField(max_length=40)),
                ('prob_desc', models.TextField()),
                ('date_desc', models.CharField(max_length=40)),
                ('cartdetails', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.cart')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
