# Generated by Django 3.2.3 on 2022-05-14 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_bookingdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repcentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.repair_centre')),
                ('usr', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='billingdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('street', models.TextField()),
                ('ph_pro', models.BigIntegerField()),
                ('det', models.TextField(max_length=80)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='addservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_addserv', models.ImageField(upload_to='media')),
                ('name_serv', models.CharField(max_length=40)),
                ('desc_serv', models.TextField()),
                ('price_serv', models.IntegerField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('adserv', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.repair_centre')),
            ],
        ),
    ]
