# Generated by Django 3.2.3 on 2022-05-23 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0019_addservices_adcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair_centre',
            name='usr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='repprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
                ('localty', models.CharField(max_length=30)),
                ('timings', models.CharField(max_length=30)),
                ('costEstimate', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=25)),
                ('directions', models.CharField(max_length=10000)),
                ('img1', models.ImageField(default='default/default restaurant.jpg', upload_to='media/restro')),
                ('img2', models.ImageField(default='default/default restaurant.jpg', upload_to='media/restro')),
                ('img3', models.ImageField(default='default/default restaurant.jpg', upload_to='media/restro')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('map', models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d227822.55035627162!2d80.8024271802209!3d26.84862299412667!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x399bfd991f32b16b%3A0x93ccba8909978be7!2sLucknow%2C%20Uttar%20Pradesh!5e0!3m2!1sen!2sin!4v1652175194751!5m2!1sen!2sin')),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.repair_centre')),
            ],
        ),
    ]
