# Generated by Django 3.2.3 on 2022-05-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20220525_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addservices',
            name='img_addserv',
            field=models.ImageField(default='default\\default_imgpro.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='service',
            name='img_ser',
            field=models.ImageField(default='default\\default_imgpro.jpg', upload_to='media'),
        ),
    ]
